### ISSUE TITLE
Cannot override manifest headers

### ISSUE THREAD

**Issue by pun-ky** [renatoathaydes/osgi-run#25] opened 2016-02-26 17:46 UTC
I am using your plugin to build my bundles but when I try to override manifest header, then incorrect value is being generated:

```

jar {
    manifest {
        instruction 'Bundle-Name', project.description
        instruction 'Bundle-SymbolicName', 'adm'
        instruction 'Private-Package', "com.mypackage.adm.api.*;version=${project.version}"
    }
}
```

MANIFEST.mf
```
Bundle-SymbolicName: com.mypackage.adm,adm
```

expected:

```
Bundle-SymbolicName: adm
```

**Comment by renatoathaydes** [comment] 2016-02-26 18:56
Hm... I don't think this is related to osgi-run, but to the `osgi` plugin. Please check with them how to fix this as I can't change this, osgi-run does not create your manifest... `osgi` does, using `bnd` behind the scenes.

**Comment by renatoathaydes** [comment] 2016-02-26 18:58
By the way, don't explicitly declare `Private-Package`.... you should only declare `Exported-Package`, the osgi plugin will generate `Private-Package` for you.

**Comment by renatoathaydes** [comment] 2016-02-29 07:13
Closing as this is not a bug in osgi-run.

**Closed by renatoathaydes** 2016-02-29 07:13 UTC
Labels: invalid

**Comment by pun-ky** [comment] 2016-03-05 18:53
yes you were right.

the correct way to override name or symbolic name is:

```
jar {
    manifest {
        name project.description
        symbolicName 'adm'
}

```

regards!
